#!/usr/bin/env ruby

require 'open3'
require 'json'

def main
  loop do
    # Read message
    message = JSON.parse read
    command = message['command']
    # Send response
    stdin, stdout, stderr, thread = Open3.popen3(command, chdir: Dir.home)
    message[:stdin] = stdin.stat.size.zero? \
      ? ''
      : stdin.read
    message[:stdout] = stdout.read
    message[:stderr] = stderr.read
    message[:status] = thread.value.to_i
    send message.to_json
  end
end

def read
  # Read the message length (first 4 bytes)
  text_length_bytes = STDIN.read 4
  exit if text_length_bytes.length.zero?
  # Unpack message length as 4 byte integer
  text_length = text_length_bytes.unpack('i').first
  # Read the text (JSON object) of the message
  text = STDIN.read text_length
end


def send message
  # Write message size
  STDOUT.write [message.bytes.size].pack('I')
  # Write the message itself
  STDOUT.write message
  STDOUT.flush
end

main
